/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/clientes': RouteRecordInfo<'/clientes', '/clientes', Record<never, never>, Record<never, never>>,
    '/eventos': RouteRecordInfo<'/eventos', '/eventos', Record<never, never>, Record<never, never>>,
    '/faturas': RouteRecordInfo<'/faturas', '/faturas', Record<never, never>, Record<never, never>>,
    '/funcionarios': RouteRecordInfo<'/funcionarios', '/funcionarios', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/quartos': RouteRecordInfo<'/quartos', '/quartos', Record<never, never>, Record<never, never>>,
    '/reservas': RouteRecordInfo<'/reservas', '/reservas', Record<never, never>, Record<never, never>>,
  }
}
